# Generated by Django 5.0.7 on 2024-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='first_name', max_length=30)),
                ('last_name', models.CharField(default='last_name', max_length=30)),
                ('customer_phone', models.BigIntegerField(default=0)),
                ('customer_email', models.EmailField(default='email', max_length=254)),
            ],
        ),
    ]
