# Generated by Django 5.0.7 on 2024-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hotel_phone', models.BigIntegerField(unique=True)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('hotel_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
