# Generated by Django 5.0.7 on 2024-08-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_hotel_description_review_room_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities', to='hotels.room', unique=True),
        ),
    ]
