# Generated by Django 5.0.7 on 2024-08-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0006_rename_customer_id_customer_id'),
        ('hotels', '0003_alter_hotel_hotel_description_review_room_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_from', models.DateField(default='1000-01-01', null=True)),
                ('booked_till', models.DateField(default='1000-01-01', null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='customer.customer')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_from', models.DateField()),
                ('booked_till', models.DateField()),
                ('payment', models.BooleanField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendingBookings', to='customer.customer')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendingBookings', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timings', to='booking.booking')),
            ],
        ),
    ]
