# Generated by Django 5.0.7 on 2024-08-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
