# Generated by Django 5.0.7 on 2024-08-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_till',
            field=models.DateField(),
        ),
    ]
