# Generated by Django 5.0.7 on 2024-08-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_booked_from_alter_booking_booked_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timings', to='booking.booking'),
        ),
    ]
