# Generated by Django 5.0.7 on 2024-08-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_timing_booking'),
        ('hotels', '0003_alter_hotel_hotel_description_review_room_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_till',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='booked_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pendingbooking',
            name='booked_till',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timing',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timing',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='CurrentBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentBookings', to='booking.booking')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentBookings', to='hotels.room', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='timing',
            name='currentBooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timings', to='booking.currentbooking'),
        ),
    ]
