# Generated by Django 5.0.7 on 2024-08-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_timing_booking_alter_booking_booked_from_and_more'),
        ('hotels', '0003_alter_hotel_hotel_description_review_room_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbooking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentBookings', to='hotels.room'),
        ),
    ]
