# Generated by Django 5.0.7 on 2024-08-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_currentbooking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='currentBooking',
        ),
        migrations.AddField(
            model_name='timing',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timings', to='booking.booking'),
        ),
        migrations.DeleteModel(
            name='CurrentBooking',
        ),
    ]
