# Generated by Django 5.0.7 on 2024-08-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_timing_currentbooking_timing_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in', to='booking.booking', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check_out',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_out', models.DateTimeField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out', to='booking.booking', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
